### PR TITLE
Update web.json

### PR DESCRIPTION
**Pull request by FerranGaallego**
Added transformation for screenReaderBrailleOutput common term support.

### CODE REVIEW

**Comment by FerranGaallego** [comment]
Thanks!



Ferran Gállego
Product development

Code Factory

We help human-technology interaction.
http://codefactoryglobal.com

**Comment by simonbates** [comment]
You are welcome. We also need to make a change to ensure that the new preference makes it through the filtering process. I'll let you know when that is done and deployed to the server.

**Comment by FerranGaallego** [comment]
Ok, thanks!



Ferran Gállego
Product development

Code Factory

We help human-technology interaction.
http://codefactoryglobal.com

**Comment by simonbates** [comment]
Done and deployed. You should now see the "access_commonprefs_c4a_enable_braille" setting (I verified with chris).

**Comment by FerranGaallego** [comment]
Great Simon, thanks!



Ferran Gállego
Product development

Code Factory

We help human-technology interaction.
http://codefactoryglobal.com

**Pull request merged**
